-- 기준 스키마(baseline).
--
-- 이 파일은 Flyway 도입 시점의 운영 스키마를 그대로 옮긴 것이다.
-- spring.flyway.baseline-on-migrate=true 이므로, 이미 테이블이 있는 데이터베이스에서는
-- 이 스크립트가 "실행되지 않고" 적용된 것으로 표시만 된다. 실제로 실행되는 곳은
-- 빈 데이터베이스뿐이다 — 새로 만드는 개발 환경, 테스트, 신규 설치.
--
-- 그래서 여기에 담아야 하는 것은 "Flyway를 붙이기 직전의 모습"이다. 그 이후의 변경은
-- V2부터 쌓는다. 이 파일을 나중에 고치면 checksum이 어긋나 기동이 막힌다.
--
-- 원본은 ddl-auto=update와 SchemaFixer들이 만들어 온 스키마를 pg_dump로 뜬 것이다.
-- 다만 두 테이블(project_progress, work_records)은 제외했다. 삭제된 기능이 남긴
-- 잔재라 대응하는 엔티티가 없고, 새 데이터베이스에까지 물려줄 이유가 없다.
-- 기존 데이터베이스에는 그대로 남아 있으며 Hibernate 검증(validate)은 매핑되지 않은
-- 테이블을 문제 삼지 않는다.

-- ── 사용자 ────────────────────────────────────────────────────────
CREATE TABLE users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              varchar(100) NOT NULL,
    email                 varchar(200) NOT NULL,
    password_hash         varchar(200) NOT NULL,
    display_name          varchar(120),
    status                varchar(20),
    withdraw_requested_at timestamp(6) with time zone,
    withdrawn_at          timestamp(6) with time zone,
    withdraw_reason       text,
    withdrawn_by          varchar(100),
    CONSTRAINT uk_users_username     UNIQUE (username),
    CONSTRAINT uk_users_email        UNIQUE (email),
    CONSTRAINT uk_users_display_name UNIQUE (display_name),
    -- NULL을 허용하는 것이 의도다. 승인제 도입 이전 행을 백필하기 전까지 NULL이었다.
    CONSTRAINT users_status_check CHECK (
        status IS NULL OR status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAW_REQUESTED', 'WITHDRAWN'))
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role    varchar(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT user_roles_role_check CHECK (role IN ('USER', 'ADMIN', 'SUPER_ADMIN'))
);

-- ── 공지 ──────────────────────────────────────────────────────────
CREATE TABLE notices (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               varchar(200) NOT NULL,
    content             text NOT NULL,
    -- 검색 전용 평문 사본. content가 HTML이라 태그가 검색에 걸리는 것을 막는다.
    content_text        text,
    content_format      varchar(10) DEFAULT 'HTML' NOT NULL,
    category            varchar(30) DEFAULT 'GENERAL' NOT NULL,
    pinned              boolean DEFAULT false NOT NULL,
    view_count          bigint DEFAULT 0 NOT NULL,
    author_username     varchar(100) NOT NULL,
    author_display_name varchar(120),
    created_at          timestamp(6) with time zone NOT NULL,
    updated_at          timestamp(6) with time zone NOT NULL,
    CONSTRAINT notices_category_check CHECK (
        category IS NULL OR category IN ('GENERAL', 'HR', 'SAFETY', 'FACILITY', 'EVENT', 'SYSTEM')),
    CONSTRAINT notices_content_format_check CHECK (
        content_format IS NULL OR content_format IN ('TEXT', 'HTML'))
);

CREATE INDEX idx_notices_pinned_id ON notices (pinned, id DESC);
CREATE INDEX idx_notices_category ON notices (category);

CREATE TABLE notice_comments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id       bigint NOT NULL,
    parent_id       bigint,
    author_username varchar(100) NOT NULL,
    content         varchar(500) NOT NULL,
    created_at      timestamp(6) with time zone NOT NULL,
    updated_at      timestamp(6) with time zone NOT NULL,
    -- Notice에 댓글 컬렉션이 없어 Hibernate가 먼저 지우지 않는다. DB가 정리해야 한다.
    CONSTRAINT fk_notice_comments_notice FOREIGN KEY (notice_id) REFERENCES notices (id) ON DELETE CASCADE,
    CONSTRAINT fk_notice_comments_parent FOREIGN KEY (parent_id) REFERENCES notice_comments (id) ON DELETE CASCADE
);

CREATE TABLE notice_attachments (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 글을 저장하기 전에 파일이 먼저 올라오므로 NULL이 될 수 있다.
    -- 붙지 못한 첨부는 NoticeAttachmentSweeper가 치운다.
    notice_id         bigint,
    kind              varchar(10) NOT NULL,
    original_filename varchar(255) NOT NULL,
    stored_filename   varchar(80) NOT NULL,
    relative_path     varchar(120) NOT NULL,
    content_type      varchar(120) NOT NULL,
    file_size         bigint NOT NULL,
    uploader_username varchar(100) NOT NULL,
    created_at        timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_notice_attachments_stored_filename UNIQUE (stored_filename),
    CONSTRAINT fk_notice_attachments_notice FOREIGN KEY (notice_id) REFERENCES notices (id) ON DELETE CASCADE,
    CONSTRAINT notice_attachments_kind_check CHECK (kind IS NULL OR kind IN ('IMAGE', 'FILE'))
);

CREATE INDEX idx_notice_attachments_notice ON notice_attachments (notice_id);
-- 고아 정리는 notice_id가 NULL인 행만 훑으므로 부분 인덱스로 둔다.
CREATE INDEX idx_notice_attachments_orphan ON notice_attachments (created_at) WHERE notice_id IS NULL;

CREATE TABLE notice_views (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id      bigint NOT NULL,
    username       varchar(100) NOT NULL,
    last_viewed_at timestamp(6) with time zone NOT NULL,
    -- 조회수 중복 방지가 ON CONFLICT (notice_id, username)에 기대므로 반드시 있어야 한다.
    CONSTRAINT uk_notice_views_notice_user UNIQUE (notice_id, username),
    CONSTRAINT fk_notice_views_notice FOREIGN KEY (notice_id) REFERENCES notices (id) ON DELETE CASCADE
);

-- ── 일정 · 할 일 ──────────────────────────────────────────────────
CREATE TABLE calendar_events (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                    date NOT NULL,
    time                    time(6) without time zone,
    title                   varchar(255) NOT NULL,
    -- scope 도입 이전 행은 NULL이며 조회 쿼리가 이를 사내 일정으로 취급한다.
    scope                   varchar(20),
    created_by_username     varchar(100),
    created_by_display_name varchar(120),
    created_at              timestamp(6) with time zone NOT NULL,
    updated_at              timestamp(6) with time zone NOT NULL,
    CONSTRAINT calendar_events_scope_check CHECK (scope IS NULL OR scope IN ('COMPANY', 'PRIVATE'))
);

CREATE TABLE todos (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL,
    date        date NOT NULL,
    title       varchar(255) NOT NULL,
    description text,
    completed   boolean NOT NULL,
    priority    integer NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_todos_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ── 적재 시뮬레이션 ───────────────────────────────────────────────
CREATE TABLE packing_scenarios (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint NOT NULL,
    name           varchar(255) NOT NULL,
    description    varchar(500),
    truck_width    integer NOT NULL,
    truck_height   integer NOT NULL,
    allow_rotate   boolean NOT NULL,
    margin         integer,
    preserve_order boolean,
    is_favorite    boolean NOT NULL,
    created_at     timestamp(6) without time zone NOT NULL,
    updated_at     timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_packing_scenarios_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE packing_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id bigint NOT NULL,
    name        varchar(255) NOT NULL,
    width       integer NOT NULL,
    height      integer NOT NULL,
    quantity    integer NOT NULL,
    sort_order  integer,
    created_at  timestamp(6) without time zone NOT NULL,
    CONSTRAINT fk_packing_items_scenario FOREIGN KEY (scenario_id) REFERENCES packing_scenarios (id)
);

-- ── 잔업 · 특근 ───────────────────────────────────────────────────
CREATE TABLE overtime_records (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL,
    -- 작성자 식별은 username 문자열로 한다. 탈퇴해도 기록이 남아야 하기 때문이다.
    username          varchar(100) NOT NULL,
    display_name      varchar(120),
    work_date         date NOT NULL,
    type              varchar(255) NOT NULL,
    start_time        time(6) without time zone,
    end_time          time(6) without time zone,
    total_minutes     integer NOT NULL,
    reason            text,
    status            varchar(255) NOT NULL,
    reject_reason     text,
    approver_username varchar(255),
    approved_at       timestamp(6) with time zone,
    created_at        timestamp(6) with time zone NOT NULL,
    updated_at        timestamp(6) with time zone NOT NULL,
    CONSTRAINT overtime_records_type_check CHECK (type IN ('OVERTIME', 'SPECIAL')),
    CONSTRAINT overtime_records_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE TABLE overtime_default_times (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       varchar(255) NOT NULL,
    start_time time(6) without time zone NOT NULL,
    end_time   time(6) without time zone NOT NULL,
    updated_by varchar(255),
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_overtime_default_times_type UNIQUE (type),
    CONSTRAINT overtime_default_times_type_check CHECK (type IN ('OVERTIME', 'SPECIAL'))
);

-- 테이블 이름이 단수인 것은 의도가 아니라 기존 스키마를 그대로 따른 것이다.
CREATE TABLE overtime_payroll_setting (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_start_day integer NOT NULL,
    updated_by      varchar(255),
    updated_at      timestamp(6) with time zone NOT NULL
);

-- ── 감사 로그 ─────────────────────────────────────────────────────
CREATE TABLE admin_logs (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_username varchar(255) NOT NULL,
    action         varchar(255) NOT NULL,
    entity_type    varchar(255) NOT NULL,
    entity_id      bigint,
    details        text,
    ip_address     varchar(255),
    timestamp      timestamp(6) with time zone NOT NULL,
    CONSTRAINT admin_logs_action_check CHECK (action IN ('CREATE', 'READ', 'UPDATE', 'DELETE'))
);

-- 조회(READ)는 양이 많아 별도 테이블에 쌓고 보존기간이 지나면 정리한다.
CREATE TABLE admin_read_logs (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_username varchar(255) NOT NULL,
    entity_type    varchar(255) NOT NULL,
    entity_id      bigint,
    details        text,
    ip_address     varchar(255),
    timestamp      timestamp(6) with time zone NOT NULL
);

CREATE INDEX idx_admin_read_logs_timestamp ON admin_read_logs (timestamp);
