CREATE TABLE vendor_categories (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(80) NOT NULL,
    active     boolean NOT NULL DEFAULT true,
    created_by varchar(100) NOT NULL,
    updated_by varchar(100) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE UNIQUE INDEX ux_vendor_categories_name_ci ON vendor_categories (lower(name));

CREATE TABLE vendors (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                       varchar(200) NOT NULL,
    category_id                bigint NOT NULL,
    business_registration_no   varchar(32),
    main_phone                 varchar(50),
    main_email                 varchar(254),
    address                    varchar(500),
    website                    varchar(500),
    memo                       text,
    created_by                 varchar(100) NOT NULL,
    updated_by                 varchar(100) NOT NULL,
    created_at                 timestamp(6) with time zone NOT NULL,
    updated_at                 timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_vendors_category FOREIGN KEY (category_id) REFERENCES vendor_categories (id)
);

CREATE INDEX idx_vendors_name ON vendors (lower(name));
CREATE INDEX idx_vendors_category_name ON vendors (category_id, lower(name));

CREATE TABLE vendor_contacts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id   bigint NOT NULL,
    name        varchar(120) NOT NULL,
    department  varchar(120),
    position    varchar(120),
    phone       varchar(50),
    mobile      varchar(50),
    email       varchar(254),
    memo        text,
    is_primary  boolean NOT NULL DEFAULT false,
    sort_order  integer NOT NULL DEFAULT 0,
    created_at  timestamp(6) with time zone NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_vendor_contacts_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id) ON DELETE CASCADE
);

CREATE INDEX idx_vendor_contacts_vendor_order ON vendor_contacts (vendor_id, sort_order, id);
CREATE INDEX idx_vendor_contacts_name ON vendor_contacts (lower(name));

INSERT INTO vendor_categories (name, active, created_by, updated_by, created_at, updated_at)
VALUES
    ('운송·택배', true, 'system', 'system', now(), now()),
    ('포장재', true, 'system', 'system', now(), now()),
    ('원자재·부품', true, 'system', 'system', now(), now()),
    ('장비·시설', true, 'system', 'system', now(), now()),
    ('외주·용역', true, 'system', 'system', now(), now()),
    ('기타', true, 'system', 'system', now(), now());
